### ISSUE TITLE
Add ARB super-committer to Community Governance doc

### ISSUE THREAD

**Issue by vmbrasseur** [tungstenfabric/docs#5]
During the TF LFN induction process, the LFN TAC provided feedback that the LF Community Governance doc should do a better job of discussing the issue of ARB members who are also "super committers" (read: have +2/-2 on Gerrit).

Please consult with Daniel Farrell for more information about the LFN TAC feedback.

**Comment by pcarver** [comment]
I think this is another reason in favor of my suggestion of replacing the ARB with a council of PTLs https://lists.tungsten.io/g/tsc/message/152 since I don't think anyone would have a major issue with PTLs having +2/-2 (or at the very least having -2 since it's pretty easy to explain that the projects within TF are very closely interconnected and code shouldn't be merged in one project over the objection of a PTL of another project that likely depends on it. The relationship between PTLs and ARB in TF is currently not very well defined.

**Comment by vmbrasseur** [comment]
Migrated to Jira: https://jira.tungsten.io/browse/TFB-1397
